### PR TITLE
add php8

### PR DESCRIPTION
**Pull request by nick-zh**
sry totally forgot this in my last pr. Please let me know if should include a nightly build in this PR

### CODE REVIEW

**Comment by tPl0ch** [comment]
@nick-zh I think we should enable travis testing for PHP 8.0, what do you think?

**Comment by tPl0ch** [comment]
@nick-zh I think PHP CS is now PHP 8 compatible, let's try with the new version?

**Comment by nick-zh** [comment]
@tPl0ch it was about `php-cs-fixer`, see https://github.com/flix-tech/schema-registry-php-client/pull/51, if the approach there is ok, we can do it like this here as well. The other PR needs to be merged first anyway, since it is used here :v:

**Comment by nick-zh** [comment]
Can you create a release of `schema-registry-php-client` so we can use it here :v:

**Comment by tPl0ch** [comment]
@nick-zh https://github.com/flix-tech/schema-registry-php-client/releases/tag/7.3.0 🥳

**Comment by tPl0ch** [comment]
Hey @nick-zh, I am actually working on PHP8 support on another branch now, because it needs some refactors in the tests as well:

https://github.com/flix-tech/avro-serde-php/pull/46

**Comment by nick-zh** [comment]
@tPl0ch thx for letting me know :+1:

**Comment by tPl0ch** [comment]
@nick-zh test https://github.com/flix-tech/avro-serde-php/releases/tag/1.7.0-rc1 pre-release with PHP 8 support 🥳

**Pull request closed without merging**
