### PR TITLE
Update `flix-tech/avro-php` dependency

### PR DESCRIPTION
**Pull request by nick-zh**
needs merge and release of
https://github.com/flix-tech/schema-registry-php-client/pull/36
first i think

### CODE REVIEW

**Comment by tPl0ch** [comment]
@nick-zh Sorry that it took so long, but now the CS-fixer task is failing. Can you give it a look?

**Comment by nick-zh** [comment]
@tPl0ch no worries, i saw your GH status, so all good. I'll check afterwards :V:

**Comment by nick-zh** [comment]
@tPl0ch issues should be fixed now :v:

**Comment by tPl0ch** [comment]
Released as https://github.com/flix-tech/avro-serde-php/releases/tag/1.4.0

**Pull request merged**
